#!/bin/bash
# This script generates a headerfile of the help document in doc/HELP.dat, part of the boes v1.1 source tree
# This script solves the issue that the Help document must be available in a to boes known directory
# As the help is not too big we just create an array of characterpointers, for each line a string
# (It may also make it easier to scroll around in the help, without fseek and fpos, just give a linenumber)

cat header.txt
count=$(awk 'END{print NR}' keywordtable.txt)
echo "/* DO NOT EDIT THIS FILE!                                             *"
echo " * This file is automatically generated by the Help_to_h.sh script.   *"
echo " * The Help_to_h.sh script converts the help file in doc/HELP.dat to  *"
echo " * this help.h file. Edit doc/HELP.dat if you want to change the help *"
echo " * text. I repeat:                                                    *"
echo " * DO NOT EDIT THIS FILE!                                             */"
echo 
echo "int NumKWT=$count;"
echo "char *KWTARR[$count] = {"
awk '{if (NR == 1) {printf "\t\"%s\"", $0 } else { printf ",\n\t\"%s\"", $0 } } END { print "" }' keywordtable.txt
echo "};"

